Add the ice40 script

diff --git a/ice40xxx/make-build/Makefile b/ice40xxx/make-build/Makefile
--- a/ice40xxx/make-build/Makefile
+++ b/ice40xxx/make-build/Makefile
@@ -7,17 +7,27 @@ filename = leds
 # build .pcf file
 pcf_file = ../common/io.pcf
 
-# build
+ICELINK_DIR=$(shell df | grep iCELink | awk '{print $$6}')
+${warning iCELink path: $(ICELINK_DIR)}
+
 build:
-	yosys -p "synth_ice40 -blif $(filename).blif" $(filename).v
-	arachne-pnr -d 5k -P sg48 -p $(pcf_file) $(filename).blif -o $(filename).asc
+	yosys -p "synth_ice40 -json $(filename).json" $(filename).v
+	nextpnr-ice40 \
+		--up5k \
+		--package sg48 \
+		--json $(filename).json \
+		--pcf $(pcf_file) \
+		--asc $(filename).asc
 	icepack $(filename).asc $(filename).bin
 
-prog: #for sram
-	iceprog -S $(filename).bin
-
 prog_flash:
-	iceprog $(filename).bin
+	@if [ -d '$(ICELINK_DIR)' ]; \
+        then \
+		cp $(filename).bin $(ICELINK_DIR); \
+        else \
+        echo "iCELink not found"; \
+        exit 1; \
+        fi
 
 clean:
-	rm -rf $(filename).blif $(filename).asc $(filename).bin
+	rm -rf *.blif *.asc *.bin *.json
